-- Create a table for Questions
create table questions (
  id bigint generated by default as identity primary key,
  question_text text not null,
  options jsonb not null, -- Stores array of strings ["A", "B", "C", "D"]
  correct_answer text not null,
  time_limit int default 15,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Create a table for Scores
create table scores (
  id bigint generated by default as identity primary key,
  player_name text not null,
  score int not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable Realtime for the scores table (so the leaderboard can update live if we add one)
alter publication supabase_realtime add table scores;
alter publication supabase_realtime add table questions;

-- Set up Row Level Security (RLS)
-- For this simple app, we will allow public read/write access.
-- WARNING: In a production app, you should restrict write access!

alter table questions enable row level security;
alter table scores enable row level security;

-- Allow anyone to read questions
create policy "Public questions are viewable by everyone."
  on questions for select
  using ( true );

-- Allow anyone to insert questions (for Admin Panel)
create policy "Public can insert questions."
  on questions for insert
  with check ( true );

-- Allow anyone to read scores
create policy "Public scores are viewable by everyone."
  on scores for select
  using ( true );

-- Allow anyone to insert scores (for Game Over)
create policy "Public can insert scores."
  on scores for insert
  with check ( true );
